-- SQL query to create the authorities table for Supabase

-- 1. Create the table to act as a master list of all available permissions
CREATE TABLE public.authorities (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT authorities_pkey PRIMARY KEY (id),
  CONSTRAINT authorities_name_key UNIQUE (name)
);

-- 2. Enable Row Level Security (RLS) for the table
ALTER TABLE public.authorities ENABLE ROW LEVEL SECURITY;

-- 3. Create policies to control access
-- Allow any authenticated user to read the list of available authorities
CREATE POLICY "Allow authenticated users to view authorities"
ON public.authorities
FOR SELECT
TO authenticated
USING (true);

-- Restrict insert, update, delete operations to only the service_role
CREATE POLICY "Allow service_role to manage authorities"
ON public.authorities
FOR ALL
TO service_role
WITH CHECK (true);

-- 5. Insert the initial set of permissions (authorities)
-- This is just an example set. You can customize it to your needs.
INSERT INTO public.authorities (name, description)
VALUES
      ('ac-authority-manager', 'Manage user authorities'),
      ('ac-edit-account', 'Allow users to edit their own account details'),
      ('fg-delivery-schedule', 'Manage FG Delivery Schedules'),
      ('fg-loading', 'Perform FG Loading'),
      ('fg-loadingdock', 'Manage FG Loading Docks'),
      ('fg-movement-history', 'View FG Movement History'),
      ('fg-outstanding', 'View Outstanding FG Deliveries'),
      ('fg-receive', 'Receive Finished Goods'),
      ('fg-stock', 'View FG Stock'),
      ('fg-upload-delivery-schedule', 'Upload FG Delivery Schedule'),
      ('fg-transporter', 'Manage FG Transporters'),
      ('pr-dashboard', 'View Paper Roll Dashboard'),
      ('pr-issue', 'Issue Paper Roll'),
      ('pr-movement-history', 'View PR Movement History'),
      ('pr-movement', 'Record Paper Roll Movement'),
      ('pr-opname-report', 'View PR Stock Opname Report'),
      ('pr-receive', 'Receive Paper Roll'),
      ('pr-return', 'Return Paper Roll'),
      ('pr-stock-opname', 'Perform PR Stock Opname'),
      ('pr-stock', 'View Paper Roll Stock'),
      ('pr-upload-stock', 'Upload Paper Roll Stock'),
      ('pr-stock-pivot', 'Analyze Paper Roll Stock with Pivot Table')
      ('pr-map', 'Paper Roll Mapping for each type')
ON CONFLICT (name) DO NOTHING;

