-- SQL query to create the fg_loading table for Supabase

-- 1. Drop the old table if it exists
DROP TABLE IF EXISTS public.fg_loading;

-- 2. Create the new table
CREATE TABLE public.fg_loading (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  so_number text NOT NULL,
  so_item text NOT NULL,
  quantity integer NOT NULL,
  truck_no text NOT NULL,
  plant text NOT NULL,
  status text,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  CONSTRAINT fg_loading_pkey PRIMARY KEY (id),
  CONSTRAINT fg_loading_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.fg_loading ENABLE ROW LEVEL SECURITY;

-- 4. Create policies for access control
CREATE POLICY "Allow authenticated users to view loading data"
ON public.fg_loading
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to insert their own loading data"
ON public.fg_loading
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);
