-- SQL query to create the fg_stock table for Supabase

-- 1. Drop the old table if it exists and you want a fresh start
-- DROP TABLE IF EXISTS public.fg_stock;

-- 2. Create the new table with the correct columns
CREATE TABLE public.fg_stock (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  lmg_number text NOT NULL,
  so_number text,
  so_item text,
  bin_location text NOT NULL,
  user_id uuid REFERENCES auth.users(id),
  plant text NOT NULL,
  CONSTRAINT fg_stock_pkey PRIMARY KEY (id)
);

-- 3. Enable Row Level Security (RLS) for the table
ALTER TABLE public.fg_stock ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to control access
CREATE POLICY "Allow authenticated users to view their own stock"
ON public.fg_stock
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Allow authenticated users to insert their own stock"
ON public.fg_stock
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);
