-- SQL query to create the pr_stock_movements table for Supabase

-- 1. Drop the old table if it exists and you want a fresh start
-- DROP TABLE IF EXISTS public.pr_stock_movements;

-- 2. Create the new table with the correct columns
CREATE TABLE public.pr_stock_movements (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  roll_id text NOT NULL,
  plant text, -- Added to specify which plant the movement belongs to
  movement_type text,
  initial_loc text,
  destination_loc text,
  batch text,
  weight numeric,
  diameter numeric,
  length numeric,
  timestamp timestamptz DEFAULT now(),
  prod_order_no text,
  user_id text,
  CONSTRAINT pr_stock_movements_pkey PRIMARY KEY (id)
);

-- 3. Enable Row Level Security (RLS) for the table
ALTER TABLE public.pr_stock_movements ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to control access
CREATE POLICY "Allow authenticated users to view their own stock movements"
ON public.pr_stock_movements
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated users to insert their own stock movements"
ON public.pr_stock_movements
FOR INSERT
TO authenticated
WITH CHECK (true);
