-- SQL query to create the pr_stock_opname_events table for Supabase

-- 1. Drop the old table if it exists and you want a fresh start
-- DROP TABLE IF EXISTS public.pr_stock_opname_events;

-- 2. Create the new table with the correct columns
CREATE TABLE public.pr_stock_opname_events (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  opname_at timestamptz NOT NULL DEFAULT now(),
  roll_id text NOT NULL,
  bin_location text NOT NULL,
  user_id uuid REFERENCES auth.users(id),
  paper_roll_id text,
  CONSTRAINT pr_stock_opname_events_pkey PRIMARY KEY (id)
);

-- 3. Enable Row Level Security (RLS) for the table
ALTER TABLE public.pr_stock_opname_events ENABLE ROW LEVEL SECURITY;

-- 4. Create policies to control access
CREATE POLICY "Allow authenticated users to view their own opname events"
ON public.pr_stock_opname_events
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Allow authenticated users to insert their own opname events"
ON public.pr_stock_opname_events
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);
